We have used more of a dynamic check at the login page and also for s…
venki17393/SessionLogin pull request #3
Opened 2017-05-19 08:05 UTC by venki17393

Here we get the email through the "get" method and not by the query. Also login page check more dynamic .
i have done the code in the catch block i will redo it using a function.

2017-05-19 08:11 UTC, ramesh-lingappan requested changes

2017-05-19 08:11 UTC, ramesh-dev commented on src/com/session/Check.java
> +		Query q1 = new Query("Contact");
again same mistake, fetching all contact and then checking each one manually is totally not the right way

2017-05-19 08:12 UTC, venki17393 commented on src/com/session/Check.java
> +		Query q1 = new Query("Contact");
okay !!! i will do as per the query

2017-05-19 12:37 UTC, ramesh-lingappan requested changes

2017-05-19 12:37 UTC, ramesh-dev commented on src/com/session/SessionHelper.java
> +	public static String  isPresent(String email){
why string as return type, if isPresent, it can possibly have two state, yes or no, you can use boolean to make it simple

2017-05-19 12:37 UTC, ramesh-dev commented on src/com/session/Check.java
> +		Filter checkEmail	= new FilterPredicate("Email", FilterOperator.EQUAL, email);
this whole check can be put in a method, also make that method return type as Entity, so if auth pass it should return fetched entity, if not return null

2017-05-23 04:35 UTC, venki17393 commented
the boolean function is performed o check if the user is already present or not

2017-05-24 15:41 UTC, closed without merging