Venkatesh dev
venki17393/SessionLogin pull request #7
Opened 2017-05-26 13:38 UTC by venki17393

The cache type of retrieval is performed where if present in URL we fetch it directly and if not present we fetch it and add it in server.. also the null request is taken care.

2017-05-27 08:43 UTC, ramesh-lingappan requested changes

2017-05-27 08:43 UTC, ramesh-dev commented on src/com/session/SessionHelper.java
>  	public static PostPojo wrongUrl() throws JSONException, JsonParseException, JsonMappingException, IOException {
what is wrongUrl , this should be here

2017-05-28 04:47 UTC, venki17393 commented
i have done the modifications  and sent the pull request

2017-05-28 06:53 UTC, ramesh-lingappan requested changes

2017-05-28 06:53 UTC, ramesh-dev commented on src/com/session/PostServlet.java
> +			int requestNumber = Integer.parseInt(path);
instead of doing exception, you already know the requestNumber can be null, so can you simply do a if condition check

2017-05-29 05:01 UTC, venki17393 commented
I have handled the null exception in using if condition, but if it is a string it will be handled in the Catch block itself

2017-05-29 08:01 UTC, merged